### PR TITLE
make the package compilable with OCaml up to 4.07

### PR DESCRIPTION
**Pull request by kandu**

### CODE REVIEW

**Comment by pdonadeo** [comment]
I'll probably merge this week end.

**Comment by kandu** [comment]
Thank you.

I did make test with "--enable-tests", with or without "--enable-luajit" on 4.02 4.04 4.06 4.07, all seems good.

**Comment by pdonadeo** [comment]
Now I "only" have to check how OPAM 2 works...

**Comment by kandu** [comment]
trick: make a local repo and add it. old version opam files will be upgraded automatically in ~/.opam/repo/local.   ;)

**Comment by pdonadeo** [comment]
@kandu you have to be patient: https://github.com/ocaml/opam-repository/pull/12888#pullrequestreview-169089501

**Pull request merged**
